# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/199CMWy2LOcxqSunHLNnA56w0f7jr1Nvd
"""

import numpy as np
import matplotlib.pyplot as plt


#Sides
PQ = 4
QR = 3.5
PR = 4

#Triangle vertices
P = np.array([0,4]) 
Q = np.array([0,0]) 
R = np.array([3.5,0]) 


#Generating all lines
x_PQ = line_gen(P,Q)
x_QR = line_gen(Q,R)
x_PR = line_gen(P,R)

#Plotting all lines
plt.plot(x_QR[0,:],x_QR[1,:],label='$QR$')
plt.plot(x_PR[0,:],x_PR[1,:],label='$PR$')
plt.plot(x_PQ[0,:],x_PQ[1,:],label='$PQ$')

plt.plot(P[0], P[1], 'o')
plt.text(P[0] * (1 + 0.1), P[1] * (1 - 0.1) , 'P')
plt.plot(Q[0], Q[1], 'o')
plt.text(Q[0] * (1 - 0.2), Q[1] * (1) , 'Q')
plt.plot(R[0], R[1], 'o')
plt.text(R[0] * (1 + 0.03), R[1] * (1 - 0.1) , 'R ')

plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid() # minor